# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "cypress-testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: 'Create env file'
      run: |
        echo "ZM_CLIENT_ID=id" > .env
        echo "ZM_CLIENT_SECRET=csecret" >> .env
        echo "ZM_REDIRECT_URL=https://example.org" >> .env
        echo "SESSION_SECRET=ssecret" >> .env
    - run: npm run build --if-present

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci

      - name: Check formatting
        run: npm run prettier:check


  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: 'Create env file'
        run: |
          echo "ZM_CLIENT_ID=id" > .env
          echo "ZM_CLIENT_SECRET=csecret" >> .env
          echo "ZM_REDIRECT_URL=https://example.org" >> .env
          echo "SESSION_SECRET=ssecret" >> .env
          echo "DATABASE_URL=test" >> .env
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
